### ISSUE TITLE
Use consistent string quoting

### ISSUE THREAD

**Issue by JarnoRFB** [justinshenk/traja#4]
Here begins the nitpicking. I noticed that we sometimes use `'` and sometimes `"`. I would be in favor of giving https://github.com/ambv/black a try to get rid of such issues once and for all.

**Comment by justinshenk** [comment]
Agreeing on a formatting convention makes sense. 

Personally, I tend to prefer single quotes for internal string literals and double quotes for presented messages, which happens to be consistent with the pandas source code. Also, for the US keyboard, single quotes are one less keystroke. 

If convenience of the developer is the primary factor, then it can be determined by the majority of `traja` contributors. So @aauss could easily tip the scales right now if he wishes. :)

**Comment by JarnoRFB** [comment]
> Personally, I tend to prefer single quotes for internal string literals and double quotes for presented messages, which happens to be consistent with the pandas source code. Also, for the US keyboard, single quotes are one less keystroke.

Ok so using different quotation based on the context the string is used in. That's new to me so I probably did not recognize it. Still I think that me might have some benefit of using a code formatter, so we don't accidentally start to reformat each others code. We could basically use whatever style is easier to write, run the formatter and be done with it. Black has apparently recently gained some popularity in the Python community, so it might be a good bet.

**Comment by justinshenk** [comment]
Sure, let's give Black a try then and perhaps add the badge to our README.

**Comment by JarnoRFB** [comment]
Cool I will do it in the evening
