### ISSUE TITLE
`trip_gird` units make no sense after binning

### ISSUE THREAD

**Issue by JarnoRFB** [justinshenk/traja#6]
Units don't match with bins in trip grid
![image](https://user-images.githubusercontent.com/8550270/52594847-ccceae00-2e4c-11e9-8253-14affbe5a285.png)

**Comment by justinshenk** [comment]
Thanks for pointing this out.

Explanation: I had tried to preserve the aspect ratio with the number of bins, but probably unnecessary. Resolved with 02678dcd43fda88a9be575401f1777199f1d6c59. Closing issue.
